(function () {
  "use strict";

    var GITHUB_USER = "kaarusdoris-a11y";
      var REPO = "DACA_portfolio";
        var REPO_BASE = "https://github.com/" + GITHUB_USER + "/" + REPO;

          // ---------- Theme toggle ----------
            var root = document.documentElement;
              var themeToggle = document.getElementById("themeToggle");
                var savedTheme = null;
                  try { savedTheme = localStorage.getItem("dk-theme"); } catch (e) {}
                    var prefersDark = window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
                      var initialTheme = savedTheme || (prefersDark ? "dark" : "light");
                        root.setAttribute("data-theme", initialTheme);
                          if (themeToggle) themeToggle.setAttribute("aria-pressed", String(initialTheme === "dark"));

                            if (themeToggle) {
                                themeToggle.addEventListener("click", function () {
                                      var current = root.getAttribute("data-theme") === "dark" ? "dark" : "light";
                                            var next = current === "dark" ? "light" : "dark";
                                                  root.setAttribute("data-theme", next);
                                                        themeToggle.setAttribute("aria-pressed", String(next === "dark"));
                                                              try { localStorage.setItem("dk-theme", next); } catch (e) {}
                                                                  });
                                                                    }

                                                                      // ---------- Mobile nav ----------
                                                                        var navToggle = document.getElementById("navToggle");
                                                                          var navLinks = document.getElementById("navLinks");
                                                                            if (navToggle && navLinks) {
                                                                                navToggle.addEventListener("click", function () {
                                                                                      var isOpen = navLinks.classList.toggle("open");
                                                                                            navToggle.setAttribute("aria-expanded", String(isOpen));
                                                                                                });
                                                                                                    navLinks.querySelectorAll("a").forEach(function (link) {
                                                                                                          link.addEventListener("click", function () {
                                                                                                                  navLinks.classList.remove("open");
                                                                                                                          navToggle.setAttribute("aria-expanded", "false");
                                                                                                                                });
                                                                                                                                    });
                                                                                                                                      }
                                                                                                                                      
                                                                                                                                        // ---------- Footer year ----------
                                                                                                                                          var yearEl = document.getElementById("year");
                                                                                                                                            if (yearEl) yearEl.textContent = new Date().getFullYear();
                                                                                                                                            
                                                                                                                                              // ---------- Reveal on scroll ----------
                                                                                                                                                var revealEls = document.querySelectorAll(".reveal");
                                                                                                                                                  if ("IntersectionObserver" in window) {
                                                                                                                                                      var io = new IntersectionObserver(
                                                                                                                                                            function (entries) {
                                                                                                                                                                    entries.forEach(function (entry) {
                                                                                                                                                                              if (entry.isIntersecting) {
                                                                                                                                                                                          entry.target.classList.add("is-visible");
                                                                                                                                                                                                      io.unobserve(entry.target);
                                                                                                                                                                                                                }
                                                                                                                                                                                                                        });
                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                    { threshold: 0.12 }
                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                            revealEls.forEach(function (el) { io.observe(el); });
                                                                                                                                                                                                                                              } else {
                                                                                                                                                                                                                                                  revealEls.forEach(function (el) { el.classList.add("is-visible"); });
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                      // ---------- Project + blog data (fallback, always accurate) ----------
                                                                                                                                                                                                                                                        var WEEKS = [
                                                                                                                                                                                                                                                            { week: 0, folder: "week-0", title: "Süsteemide seadistamine", desc: "GitHub, Supabase ja NotebookLM töökeskkonna ülesseadmine meeskonnale.", file: "WEEK0_README.md" },
                                                                                                                                                                                                                                                                { week: 1, folder: "week-1", title: "SQL põhitõed", desc: "SELECT, WHERE, DISTINCT, COUNT — esimesed päringud UrbanStyle müügiandmetel.", file: "WEEK1_README.md" },
                                                                                                                                                                                                                                                                    { week: 2, folder: "week-2", title: "SQL andmepuhastus", desc: "Duplikaadid, NULL-id ja vormingud — 5116 duplikaatrea eemaldamine.", file: "WEEK2_README.md" },
                                                                                                                                                                                                                                                                        { week: 3, folder: "week-3", title: "SQL JOINs", desc: "INNER JOIN, LEFT JOIN, mitme tabeli päringud kliendi- ja tootekäitumise analüüsiks.", file: "WEEK3_README.md" },
                                                                                                                                                                                                                                                                            { week: 4, folder: "week-4", title: "SQL agregatsioon", desc: "GROUP BY, HAVING, CTE-d ja window functions juhatuse koosoleku numbrite jaoks.", file: "WEEK4_README.md" },
                                                                                                                                                                                                                                                                                { week: 5, folder: "week-5", title: "Dashboard disain", desc: "Diagrammitüübid, visuaalne hierarhia ja interaktiivne Plotly + Streamlit dashboard.", file: "WEEK5_README.md" },
                                                                                                                                                                                                                                                                                    { week: 6, folder: "week-6", title: "Andmelood", desc: "Annotatsioonid ja \"ja mis siis?\" meetod — numbritest veenva narratiivini.", file: "WEEK6_README.md" },
                                                                                                                                                                                                                                                                                        { week: 7, folder: "week-7", title: "RFM-analüüs Pythonis", desc: "pandas + Plotly: VIP-kliendid, lahkumisrisk ja kampaaniate sihtimine.", file: "WEEK7_README.md" },
                                                                                                                                                                                                                                                                                            { week: 8, folder: "week-8", title: "Python API pipeline", desc: "Supabase Python client, automatiseeritud ETL-pipeline ja logimine.", file: "WEEK8_README.md" },
                                                                                                                                                                                                                                                                                                { week: 9, folder: "week-9", title: "Peer review", desc: "Kaaslaste töö ülevaatus ja tagasiside andmine.", file: "WEEK9_peer_review_roll_B.md" },
                                                                                                                                                                                                                                                                                                    { week: 10, folder: "week-10", title: "Portfoolio kaitsmine", desc: "Grupiprojekti kokkuvõte ja individuaalne portfoolio kaitsmine.", file: "README.md" }
                                                                                                                                                                                                                                                                                                      ];
                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                        function cardHtml(w) {
                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                  '<a class="project-card" href="' + REPO_BASE + "/tree/main/" + w.folder + '" target="_blank" rel="noopener">' +
                                                                                                                                                                                                                                                                                                                        '<span class="project-week">Nädal ' + w.week + "</span>" +
                                                                                                                                                                                                                                                                                                                              "<h3>" + w.title + "</h3>" +
                                                                                                                                                                                                                                                                                                                                    "<p>" + w.desc + "</p>" +
                                                                                                                                                                                                                                                                                                                                          '<span class="project-link">Vaata GitHubis →</span>' +
                                                                                                                                                                                                                                                                                                                                                "</a>"
                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                        function blogItemHtml(w) {
                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                  '<a class="blog-item" href="' + REPO_BASE + "/blob/main/" + w.folder + "/" + w.file + '" target="_blank" rel="noopener">' +
                                                                                                                                                                                                                                                                                                                                                                        '<span class="blog-title">Nädal ' + w.week + " — " + w.title + "</span>" +
                                                                                                                                                                                                                                                                                                                                                                              '<span class="blog-arrow">→</span>' +
                                                                                                                                                                                                                                                                                                                                                                                    "</a>"
                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                            function renderProjects(weeks) {
                                                                                                                                                                                                                                                                                                                                                                                                var grid = document.getElementById("projectGrid");
                                                                                                                                                                                                                                                                                                                                                                                                    if (!grid) return;
                                                                                                                                                                                                                                                                                                                                                                                                        grid.innerHTML = weeks.map(cardHtml).join("");
                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                            function renderBlog(weeks) {
                                                                                                                                                                                                                                                                                                                                                                                                                var list = document.getElementById("blogList");
                                                                                                                                                                                                                                                                                                                                                                                                                    if (!list) return;
                                                                                                                                                                                                                                                                                                                                                                                                                        list.innerHTML = weeks.map(blogItemHtml).join("");
                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                            // Render fallback immediately so the page is never empty
                                                                                                                                                                                                                                                                                                                                                                                                                              renderProjects(WEEKS);
                                                                                                                                                                                                                                                                                                                                                                                                                                renderBlog(WEEKS);
                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                  // ---------- Optional: verify live folder list via GitHub API ----------
                                                                                                                                                                                                                                                                                                                                                                                                                                    // If the repo structure changes, this keeps the project grid honest.
                                                                                                                                                                                                                                                                                                                                                                                                                                      // Falls back silently to the static WEEKS list above on any error/rate-limit.
                                                                                                                                                                                                                                                                                                                                                                                                                                        fetch("https://api.github.com/repos/" + GITHUB_USER + "/" + REPO + "/contents/")
                                                                                                                                                                                                                                                                                                                                                                                                                                            .then(function (res) { if (!res.ok) throw new Error("GitHub API unavailable"); return res.json(); })
                                                                                                                                                                                                                                                                                                                                                                                                                                                .then(function (items) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      var folders = items
                                                                                                                                                                                                                                                                                                                                                                                                                                                              .filter(function (item) { return item.type === "dir" && /^week-\d+$/.test(item.name); })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .map(function (item) { return item.name; });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!folders.length) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  var liveWeeks = WEEKS.filter(function (w) { return folders.indexOf(w.folder) !== -1; });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (liveWeeks.length) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                liveWeeks.sort(function (a, b) { return a.week - b.week; });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderProjects(liveWeeks);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                renderBlog(liveWeeks);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .catch(function () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /* keep static fallback already rendered */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
